[profile.default]
solc_version = '0.8.23'
optimizer = false
src = 'src'
out = 'out'
libs = ['lib']

[profile.optimized]
optimizer = true
optimizer_runs = 100000

[fmt]
line_length=130
tab_width=4
func_attrs_with_params_multiline=true
